const qForm=document.querySelector('#quote-form'),qDoc=document.querySelector('#quote-document');
const qEscape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const quotationPages={
 scope:{date:'10-09-2025',title:'Off plan project',subtitle:'Villa visualization',services:[
  {name:'Immersive Drone Video Teaser',price:15000000,body:'One immersive project video teaser, approximately 30/45s long, designed for social media, investor presentations, website use, and sales communication.',list:['Standard drone shots','FPV drone shots & top-down views','Lifestyle shots','Augmented renders','Land and surroundings footage','Clear graphic annotations','Motion effects and visual transitions','Integration of selected project renders or villa visuals'],after:'FPV drone footage will be captured using an immersive drone setup, creating dynamic movement through the land and surroundings for a stronger sense of scale, access, height, and location. Classic and FPV drone footage will be combined with top-down views, clear annotations, render integration, and light AI-assisted effects to present the land, project positioning, access, scale, surroundings, and overall project vision in a premium 1-minute video. The final teaser will be ready for social media, investor updates, advertising, private presentations, and project promotion.'},
  {name:'Photo Content',price:8000000,body:'Professional photos of the land, surroundings, access points, key viewpoints, drone perspectives, and project context.',after:'Usable for brochures, social media, investor updates, website content, and sales presentations.'}
 ]},
 spatial:{date:'30-06-2025',title:'Virtual tour & video',subtitle:'Project visualization',services:[
  {name:'360° Land Mapping & Virtual Tour',price:8000000,body:'Real 360° mapping of the land, captured on-site with drone and 360° equipment, showing the current state of the property and its surroundings.',list:['Interactive navigation across the land, including access points, roads, viewpoints, future villa zones, surrounding environment, and main points of interest.','Top-down master view of the project, helping investors and clients understand the full property layout, dimensions, positioning, and general land organization.','Clear visual annotations directly inside the Virtual Tour, including project zones, villa positioning, access points, views, surroundings, and contextual information.','Integration of the masterplan and project information to connect the existing land and future development.','Website-ready shareable link, accessible on mobile, tablet, and desktop, for sales presentations, investor updates, website integration, or private sharing.']},
  {name:'360° Villa Interior Visualization',price:10000000,body:'360° interior visualization of selected villa spaces, created from the final renders and visual materials provided by the client’s renders team.',after:'Custom hotspots will connect the land navigation to the villa interior views, creating a smoother and more immersive project presentation. The selection of villa interiors and viewpoints will be discussed and defined with the client’s team before production.'}
 ]}
};
const qParams=new URLSearchParams(location.search);for(const name of ['logo','layout','mode']){const el=qForm.elements[name];if([...el.options].some(o=>o.value===qParams.get(name)))el.value=qParams.get(name);}
function renderQuote(){const data=new FormData(qForm),logo=data.get('logo'),layout=data.get('layout'),mode=data.get('mode'),page=quotationPages[layout];if(!page||!['editorial','signal','studio'].includes(logo))return;
 qDoc.className='quote-document '+layout+' '+logo;qDoc.dataset.logo=logo;qDoc.dataset.layout=layout;qDoc.dataset.mode=mode;
 const invoice=mode==='invoice';
 qDoc.innerHTML=`<div class="document-top"><img src="logos/${logo}-ink.svg" alt="Meta Pacific ${logo} logo"><div><strong>${invoice?'INVOICE / EXAMPLE':'QUOTATION'}</strong><span>REAL ESTATE SERVICES</span></div></div><div class="document-meta"><div><span>FROM</span><strong>PT. INDO META PACIFC</strong><span>TO</span><strong>${qEscape(data.get('client'))}</strong></div><div><span>${invoice?'SOURCE QUOTATION':'QUOTATION'} REFERENCE</span><strong>${qEscape(data.get('reference'))}</strong><span>${invoice?'SOURCE DATE':'DATE'}</span><strong>${page.date}</strong></div></div><div class="document-title"><h1>${page.title}</h1><p>${page.subtitle}</p></div><div class="document-services">${page.services.map((s,i)=>`<section class="document-service"><div class="service-title"><span class="service-index">0${i+1}</span><h2>${s.name}</h2><div class="service-price"><small>IDR</small><strong>${new Intl.NumberFormat('en-US').format(s.price)}</strong></div></div><p>${s.body}</p>${s.list?`<ul>${s.list.map(x=>`<li>${x}</li>`).join('')}</ul>`:''}${s.after?`<p>${s.after}</p>`:''}</section>`).join('')}</div><div class="document-credit"><span>${invoice?'DESIGN EXAMPLE / NOT AN ISSUED INVOICE':'QUOTATION #578 / LAYOUT STUDY'}</span><span>Jerio</span></div>`;
 document.title=`${invoice?'Invoice-example':'Quotation'}-${logo}-${layout}-Jerio`;
 document.querySelector('#reference-download').href=`pdf/quotation-${logo}-${layout}-Jerio.pdf`;
}
qForm.addEventListener('input',renderQuote);qForm.addEventListener('change',renderQuote);qForm.addEventListener('submit',e=>{e.preventDefault();if(qForm.reportValidity())window.print();});document.querySelector('#quote-reset').addEventListener('click',()=>{qForm.elements.client.value='PRIVATE OWNER';qForm.elements.reference.value='578';renderQuote();});renderQuote();
