// ponytail: native animation and observers keep the graphic layer independent of content.
(()=>{
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 // Drawn paths, not font characters: identical silhouettes on iOS, Android and desktop.
 const mouth=`<svg class="abstract-mouth" viewBox="0 0 400 240" aria-hidden="true" focusable="false"><path class="mouth-shadow" d="M20 124C80 91 124 95 195 112C257 93 324 100 380 124C320 163 269 185 204 187C125 184 75 159 20 124Z" fill="#121212"/><g class="lip-upper"><path fill="currentColor" d="M20 124C75 108 104 48 149 43C172 40 191 62 205 65C224 63 240 38 260 48C307 72 339 108 380 124C301 116 252 101 205 115C151 98 89 113 20 124Z"/><path d="M62 109C104 91 126 63 151 60M85 108C119 93 140 74 156 73M110 106L160 87M145 103L177 97M220 96L237 74M244 95L260 72M267 100L280 86M291 105L300 99" fill="none" stroke="#121212" stroke-width="3" stroke-linecap="round"/></g><g class="lip-lower"><path fill="currentColor" d="M20 124C88 155 144 166 204 165C266 163 328 142 380 124C333 169 287 213 216 215C133 221 77 182 20 124Z"/><path d="M79 164L108 183M106 173L130 197M137 181L151 204M169 185L175 208M204 188L204 209M235 184L230 207M266 176L252 202M296 165L275 190M320 155L298 177" fill="none" stroke="#121212" stroke-width="3" stroke-linecap="round"/></g><path class="mouth-glint" d="M123 128Q204 109 281 125L265 144Q202 157 139 143Z" fill="#f8f8f8"/><path d="M170 121L173 147M207 119L207 150M242 121L239 147" stroke="#121212" stroke-width="2" fill="none"/></svg>`;
 document.querySelectorAll('.social-art .symbol,.hero-star,.graphic-cut').forEach(el=>{el.innerHTML=mouth;el.classList.add('mouth-art');});
 const pause=document.createElement('button');pause.type='button';pause.className='motion-pause';pause.textContent='Pause motion';pause.setAttribute('aria-pressed','false');if(document.querySelector('.abstract-mouth,.graphic-orbit,.optical-disc,.contact-orbit'))document.querySelector('footer')?.append(pause);
 let pausedEntrances=[];
 pause.addEventListener('click',()=>{const paused=document.body.classList.toggle('motion-paused');pause.textContent=paused?'Resume motion':'Pause motion';pause.setAttribute('aria-pressed',String(paused));if(paused){pausedEntrances=document.getAnimations().filter(a=>!('animationName' in a)&&a.playState==='running');pausedEntrances.forEach(a=>a.pause());}else{pausedEntrances.filter(a=>a.playState==='paused').forEach(a=>a.play());pausedEntrances=[];}});
 function motionPreference(){pause.hidden=reduced.matches;if(reduced.matches)document.getAnimations().filter(a=>!('animationName' in a)).forEach(a=>a.cancel());}motionPreference();
 const ease='cubic-bezier(.16,1,.3,1)';
 function animateScene(scene){if(reduced.matches||document.body.classList.contains('motion-paused'))return;const eye=scene.querySelector('.graphic-eye,.cutout-eye'),cut=scene.querySelector('.graphic-cut,.hero-star'),photo=scene.querySelector('.hero-window,.hero-art>img');if(eye)eye.animate([{scale:.35,rotate:'-35deg'},{scale:1,rotate:'0deg'}],{duration:1200,easing:ease});if(cut)cut.animate([{rotate:'-100deg',scale:.65},{rotate:'0deg',scale:1}],{duration:2800,easing:ease});if(photo)photo.animate([{clipPath:'inset(0 0 100% 0)'},{clipPath:getComputedStyle(photo).clipPath}],{duration:1350,easing:ease});}
 document.querySelectorAll('.graphic-scene').forEach(animateScene);
 document.querySelector('#identity-select')?.addEventListener('change',()=>document.querySelectorAll('.graphic-scene').forEach(scene=>{scene.querySelectorAll('*').forEach(el=>el.getAnimations().filter(a=>!('animationName' in a)).forEach(a=>a.cancel()));animateScene(scene);}));
 document.querySelectorAll('.kinetic-title').forEach(title=>{const walker=document.createTreeWalker(title,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){const fragment=document.createDocumentFragment();for(const word of node.textContent.split(/(\s+)/)){if(!word.trim()){fragment.append(word);continue;}const span=document.createElement('span');span.className='kinetic-word';span.textContent=word;fragment.append(span);}node.replaceWith(fragment);}});
 const response=document.querySelector('#phase-content');
 if(response&&document.body.dataset.task){const blocks=[...response.querySelectorAll('.phase-block:not(.print-grid-overview)')];const nav=document.createElement('nav');nav.className='response-nav';nav.setAttribute('aria-label','Within this response');const label=document.createElement('label');label.textContent='Jump to';const select=document.createElement('select');select.setAttribute('aria-label','Section in this response');const placeholder=new Option('Choose a section','');select.append(placeholder);blocks.forEach((block,i)=>{block.id='response-'+(i+1);const option=document.createElement('option');option.value=block.id;option.textContent=block.querySelector('h2').textContent;select.append(option);});label.append(select);nav.append(label);const context=document.createElement('span');context.textContent='One response. Its own PDF.';nav.append(context);response.querySelector('.phase-head').after(nav);select.addEventListener('change',()=>{const target=document.getElementById(select.value);if(!target)return;target.scrollIntoView({behavior:reduced.matches?'instant':'smooth',block:'start'});const title=target.querySelector('h2');title.tabIndex=-1;title.focus({preventScroll:true});select.value='';});}
 const sections=[...document.querySelectorAll('.task-chapter')],nav=document.querySelector('.chapter-nav');
 if(nav){const observer=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>a.boundingClientRect.top-b.boundingClientRect.top)[0];if(!visible)return;nav.querySelectorAll('a').forEach(a=>{if(a.hash==='#'+visible.target.id)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});},{rootMargin:'-15% 0px -55% 0px',threshold:0});sections.forEach(s=>observer.observe(s));}
 const progress=document.createElement('div');progress.className='reading-progress';progress.setAttribute('aria-hidden','true');document.body.append(progress);let ticking=false;function update(){const total=document.documentElement.scrollHeight-innerHeight;progress.style.transform='scaleX('+(total>0?Math.min(1,scrollY/total):0)+')';ticking=false;}addEventListener('scroll',()=>{if(!ticking&&!reduced.matches){ticking=true;requestAnimationFrame(update);}},{passive:true});update();
 reduced.addEventListener('change',motionPreference);
})();
