const identitySelect=document.querySelector('#identity-select');
const identities={editorial:{headline:'A place.<br><span>A point of view.</span>'},signal:{headline:'FROM THE OUTSIDE.<br><span>IN.</span>'},studio:{headline:'We make places<br><span>make sense.</span>'}};
const motionPreference=matchMedia('(prefers-reduced-motion: reduce)');
function entrance(){document.querySelectorAll('.hero-heading,.hero-window img').forEach(el=>el.getAnimations().filter(a=>!('animationName' in a)).forEach(a=>a.cancel()));if(motionPreference.matches||document.body.classList.contains('motion-paused'))return;document.querySelector('.hero-heading').animate([{translate:'0 22px'},{translate:'0 0'}],{duration:900,easing:'cubic-bezier(.16,1,.3,1)'});document.querySelector('.hero-window img').animate([{scale:1.055},{scale:1}],{duration:4400,easing:'cubic-bezier(.16,1,.3,1)'});}
function setIdentity(value){const identity=identities[value]?value:'editorial';document.body.dataset.identity=identity;identitySelect.value=identity;document.querySelector('#landing-headline').innerHTML=identities[identity].headline;document.querySelectorAll('[data-brand]').forEach(img=>{img.src=`logos/${identity}-${img.dataset.tone||'ink'}.svg`;});const url=new URL(location.href);url.searchParams.set('logo',identity);history.replaceState(null,'',url);entrance();}
identitySelect.addEventListener('change',()=>setIdentity(identitySelect.value));setIdentity(new URLSearchParams(location.search).get('logo'));
const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){if(!motionPreference.matches&&!document.body.classList.contains('motion-paused'))entry.target.animate([{scale:1.045},{scale:1}],{duration:3600,easing:'cubic-bezier(.16,1,.3,1)'});observer.unobserve(entry.target);}},{threshold:.15});document.querySelectorAll('.motion-shot:not(.hero-window img)').forEach(img=>observer.observe(img));
motionPreference.addEventListener('change',e=>{if(e.matches)document.getAnimations().filter(a=>!('animationName' in a)).forEach(a=>a.cancel());});
const projects={sakti:{title:'Sakti / FPV',image:'assets/work/sakti-fpv.jpg',copy:'A project view from the Meta Pacific FPV collection. Flight planning connects the setting, the approach and the spaces within.'},samui:{title:'Koh Samui / Hospitality',image:'assets/work/kohsamui-fpv.jpg',copy:'A villa interior from the Meta Pacific project collection. The opening, the light and the connected spaces give the viewer a sense of the place.'},anjuna:{title:'Anjuna / Virtual tour',image:'artwork/anjuna-master-live.png',copy:'A project you can explore from the coastal overview to construction phases and proposed villa spaces. Open the tour to choose a viewpoint.'}};
const dialog=document.querySelector('#project-dialog');let trigger;
document.querySelectorAll('[data-project]').forEach(button=>button.addEventListener('click',()=>{const project=projects[button.dataset.project];if(!project)return;trigger=button;document.querySelector('#project-title').textContent=project.title;document.querySelector('#project-copy').textContent=project.copy;const img=document.querySelector('#project-image');img.src=project.image;img.alt=project.title;document.querySelector('#project-tour').hidden=button.dataset.project!=='anjuna';dialog.showModal();}));
document.querySelector('#project-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>trigger?.focus());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});document.querySelector('#project-tour').addEventListener('click',()=>dialog.close());
const tourSteps=[...document.querySelectorAll('.tour-step')];
const tourPreview=document.querySelector('#tour-preview');
const tourLabels=['Captured site / Coastal overview','Captured site / Palms, labelled September 2026 in the tour','Proposed villa / Rendered interior'];
let currentTour=0,manualTourY=null;
function showTour(index){if(index===currentTour)return;currentTour=index;const source=tourSteps[index].querySelector('img');tourPreview.src=source.getAttribute('src');tourPreview.alt=source.alt;document.querySelector('#tour-caption').textContent=tourLabels[index];document.querySelectorAll('[data-tour-view]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.tourView)===index)));if(!motionPreference.matches&&!document.body.classList.contains('motion-paused')){tourPreview.getAnimations().forEach(a=>a.cancel());tourPreview.animate([{clipPath:'inset(0 0 0 100%)'},{clipPath:'inset(0)'}],{duration:450,easing:'cubic-bezier(.16,1,.3,1)'});}}
document.querySelectorAll('[data-tour-view]').forEach(button=>button.addEventListener('click',()=>{manualTourY=scrollY;showTour(Number(button.dataset.tourView));}));
// ponytail: only three step bounds, and only while the tour is in view.
function followTour(){if(innerWidth<1024)return;if(manualTourY!==null){if(Math.abs(scrollY-manualTourY)<8)return;manualTourY=null;}const section=document.querySelector('#experience').getBoundingClientRect();if(section.bottom<0||section.top>innerHeight)return;let index=0;tourSteps.forEach((step,i)=>{if(step.getBoundingClientRect().top<=innerHeight*.45)index=i;});showTour(index);}
addEventListener('scroll',followTour,{passive:true});
addEventListener('resize',followTour);
