const identitySelect=document.querySelector('#identity-select');
const identities={editorial:{headline:'Show the place.<br><span>Then take us inside.</span>'},signal:{headline:'Get closer.<br><span>Before you get here.</span>'},studio:{headline:'Film the place.<br><span>Build the experience.</span>'}};
const motionPreference=matchMedia('(prefers-reduced-motion: reduce)');
function entrance(){document.querySelectorAll('.hero-heading,.hero-window img').forEach(el=>el.getAnimations().forEach(a=>a.cancel()));if(motionPreference.matches)return;document.querySelector('.hero-heading').animate([{translate:'0 22px'},{translate:'0 0'}],{duration:900,easing:'cubic-bezier(.16,1,.3,1)'});document.querySelector('.hero-window img').animate([{scale:1.055},{scale:1}],{duration:4400,easing:'cubic-bezier(.16,1,.3,1)'});}
function setIdentity(value){const identity=identities[value]?value:'editorial';document.body.dataset.identity=identity;identitySelect.value=identity;document.querySelector('#landing-headline').innerHTML=identities[identity].headline;document.querySelectorAll('[data-brand]').forEach(img=>{img.src=`logos/${identity}-${img.dataset.tone||'ink'}.svg`;});const url=new URL(location.href);url.searchParams.set('logo',identity);history.replaceState(null,'',url);entrance();}
identitySelect.addEventListener('change',()=>setIdentity(identitySelect.value));setIdentity(new URLSearchParams(location.search).get('logo'));
const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){if(!motionPreference.matches)entry.target.animate([{scale:1.045},{scale:1}],{duration:3600,easing:'cubic-bezier(.16,1,.3,1)'});observer.unobserve(entry.target);}},{threshold:.15});document.querySelectorAll('.motion-shot:not(.hero-window img)').forEach(img=>observer.observe(img));
motionPreference.addEventListener('change',e=>{if(e.matches)document.getAnimations().forEach(a=>a.cancel());});
const projects={sakti:{title:'Sakti / FPV',image:'assets/work/sakti-fpv.jpg',copy:'A project view from the Meta Pacific FPV collection. Flight planning connects the setting, the approach and the spaces within.'},samui:{title:'Koh Samui / Hospitality',image:'assets/work/kohsamui-fpv.jpg',copy:'A villa interior from the Meta Pacific project collection. The opening, the light and the connected spaces give the viewer a sense of the place.'},anjuna:{title:'Anjuna / Virtual tour',image:'artwork/anjuna-master-live.png',copy:'A project you can explore from the coastal overview to construction phases and proposed villa spaces. Open the tour to choose a viewpoint.'}};
const dialog=document.querySelector('#project-dialog');let trigger;
document.querySelectorAll('[data-project]').forEach(button=>button.addEventListener('click',()=>{const project=projects[button.dataset.project];if(!project)return;trigger=button;document.querySelector('#project-title').textContent=project.title;document.querySelector('#project-copy').textContent=project.copy;const img=document.querySelector('#project-image');img.src=project.image;img.alt=project.title;document.querySelector('#project-tour').hidden=button.dataset.project!=='anjuna';dialog.showModal();}));
document.querySelector('#project-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>trigger?.focus());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});document.querySelector('#project-tour').addEventListener('click',()=>dialog.close());
